#!/bin/env python3 

import sys, serial
from relay import Relay

nanoRelayUSB = '/dev/ttyUSB0'
baudrate = 9600 
codec = 'utf-8'
lastState = 0b11111111
currentState = 0b11111111
numberOfRelays = 8

if __name__ == '__main__':
    try:
        nanoRelay = serial.Serial(nanoRelayUSB, baudrate, timeout=1)
        nanoRelay.flush()

        relays = []
        for _ in range(numberOfRelays):
            relays.append(Relay(_))

        while True:
            if nanoRelay.in_waiting > 0:
                state = nanoRelay.readline().decode(codec).rstrip()
                currentState = int(state)
            if currentState != lastState:
                print(currentState)
                Relay.state = currentState
                for relay in relays:
                    if relay.isOn():
                        print('Relay number ', relay.getNumber(), 'is on')
                lastState = currentState
    except KeyboardInterrupt:
        print('Interrupted')
        sys.exit(0)

